### ISSUE TITLE
Feedback: implement additional config parameters

### ISSUE THREAD

**Issue by simon-p-r** [daraosn/hapi-rest-methods#1]
Hi

Just following your comment on discuss, my feedback is you are missing these [features](http://hapijs.com/api#route-options), maybe this could be second parameter of your api.

Thanks

**Comment by daraosn** [comment]
Working on it, thanks for the feedback!

**Comment by simon-p-r** [comment]
Nice idea

**Comment by daraosn** [comment]
Done
